### ISSUE TITLE
Error in Command

### ISSUE THREAD

**Issue by chnaski** [ZeLarpMaster/ZeCogs#28]
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/redbot/cogs/birthdays.py", line 137, in bday_list
    await self.bot.send_message(channel, embed=embed)
  File "/home/redbot/red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

[09/06/2019 22:04] ERROR red on_command_error 369: Exception in command 'bday list'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/redbot/cogs/birthdays.py", line 137, in bday_list
    await self.bot.send_message(channel, embed=embed)
  File "/home/redbot/red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

**Comment by ZeLarpMaster** [comment]
That traceback doesn't tell me much. Can you send me your birthdays config in private on Discord so I can try and see what happened? You can find me on Red's cog support server or on Red's server.

**Comment by chnaski** [comment]
sent

**Comment by ZeLarpMaster** [comment]
The issue was caused by having too many birthdays, created an issue for that: #29
